fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    epel: "git@github.com:stahnma/puppet-module-epel.git"
    inifile: "git@github.com:puppetlabs/puppetlabs-inifile.git"
  symlinks:
    ec2tagfacts: "#{source_dir}"
